### ISSUE TITLE
Project Completion Checklist

### ISSUE THREAD

**Issue by grey-r** [grey-r/chat#1]
In order of priority:

- [x] Infinite scrollback / pagination
- [x] Markdown
- [x] Image Uploading
- [x] Role Based Access Control 
- [ ] VADER Sentiment 
- [ ] Message Deletion (+view deleted message IDs API)
- [ ] Image Link Embeds
- [ ] Rank/Promotion UI
- [ ] CSS Polish (switch to Bootstrap? potential ref -- https://mdbootstrap.com/plugins/jquery/chat/)

**Comment by theafriquinn** [comment]
- [ ] Change slider, find VADER sentiment brackets

**Comment by grey-r** [comment]
- [ ] Profanity Filter
- [ ] XHR Request Filtering
- [ ] Username trim, channel name trim, length checks
